"""T5Gemma2 text encoder config — embedded constant.

Source: HuggingFace Motif-Technologies/Motif-Video-2B, text_encoder/config.json
(commit 시점 2026-04-24, 3596 bytes).

이전에는 `text_encoders/config.json` 파일을 loader 가 런타임에 읽었으나,
본 상수 내장으로 파일 I/O 와 디렉토리 탐색 의존을 제거했다.
"""

from __future__ import annotations

T5_GEMMA2_CONFIG: dict = {
    "architectures": [
        "T5Gemma2Encoder"
    ],
    "attention_dropout": 0.0,
    "boi_token_index": 255999,
    "dropout_rate": 0.0,
    "dtype": "bfloat16",
    "eoi_token_index": 256000,
    "image_token_index": 256001,
    "initializer_range": 0.02,
    "mm_tokens_per_image": 256,
    "model_type": "t5gemma2_encoder",
    "text_config": {
        "_sliding_window_pattern": 6,
        "add_cross_attention": False,
        "attention_bias": False,
        "attention_dropout": 0.0,
        "attn_logit_softcapping": None,
        "bos_token_id": 2,
        "cross_attention_hidden_size": None,
        "decoder_start_token_id": None,
        "dropout_rate": 0.0,
        "dtype": "bfloat16",
        "eos_token_id": 1,
        "final_logit_softcapping": None,
        "finetuning_task": None,
        "head_dim": 256,
        "hidden_activation": "gelu_pytorch_tanh",
        "hidden_size": 2560,
        "initializer_range": 0.02,
        "intermediate_size": 10240,
        "is_decoder": False,
        "layer_types": [
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "full_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "full_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "full_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "full_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "full_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
            "sliding_attention",
        ],
        "max_position_embeddings": 131072,
        "model_type": "t5gemma2_text",
        "num_attention_heads": 8,
        "num_hidden_layers": 34,
        "num_key_value_heads": 4,
        "pad_token_id": 0,
        "prefix": None,
        "query_pre_attn_scalar": 256,
        "rms_norm_eps": 1e-06,
        "rope_parameters": {
            "full_attention": {
                "factor": 8.0,
                "rope_theta": 1000000,
                "rope_type": "linear",
            },
            "sliding_attention": {
                "rope_theta": 10000,
                "rope_type": "default",
            },
        },
        "sep_token_id": None,
        "sliding_window": 1024,
        "task_specific_params": None,
        "tie_encoder_decoder": False,
        "tie_word_embeddings": True,
        "tokenizer_class": None,
        "use_bidirectional_attention": False,
        "use_cache": True,
        "vocab_size": 262144,
    },
    "tie_word_embeddings": True,
    "transformers_version": "5.5.4",
    "vision_config": {
        "add_cross_attention": False,
        "attention_dropout": 0.0,
        "bos_token_id": None,
        "cross_attention_hidden_size": None,
        "decoder_start_token_id": None,
        "dropout_rate": 0.0,
        "dtype": "bfloat16",
        "eos_token_id": None,
        "finetuning_task": None,
        "hidden_act": "gelu_pytorch_tanh",
        "hidden_size": 1152,
        "image_size": 896,
        "intermediate_size": 4304,
        "is_decoder": False,
        "layer_norm_eps": 1e-06,
        "model_type": "siglip_vision_model",
        "num_attention_heads": 16,
        "num_channels": 3,
        "num_hidden_layers": 27,
        "pad_token_id": None,
        "patch_size": 14,
        "prefix": None,
        "sep_token_id": None,
        "task_specific_params": None,
        "tie_encoder_decoder": False,
        "tie_word_embeddings": True,
        "tokenizer_class": None,
        "vision_use_head": False,
        "vocab_size": 262144,
    },
    "vocab_size": 262144,
}
