"""P5.2 fp16 smoke entrypoint. Runs on a GPU pod.

Loads the MotifVideo transformer with weight_dtype=float16, runs one forward
pass with the shared seeded input (generated by P5.1 if not already present),
and writes:
  - logs/p5_2_fp16_smoke.log   — required verify fields

NOTE: P5.2 does NOT save a baseline tensor. P5.4 cosine similarity uses
the bf16 baseline written by P5.1 (p5_1_bf16_output.pt).

Required log fields (checked by checklist verify commands):
  weight_dtype=float16
  output_shape=[...]
  nan_count=0
  inf_count=0
  STATUS=OK
"""
from __future__ import annotations

import sys
import time
import traceback

import torch

from tests.transformer.gpu_scripts._common import (
    CHECKPOINT_PATH,
    ensure_logs_dir,
    generate_or_load_input_seed,
    count_nan_inf,
    shape_str,
    _log_line,
    load_transformer_fp16,
    assert_attn_weights_loaded,
)


def main() -> int:
    logs = ensure_logs_dir()
    log_path = logs / "p5_2_fp16_smoke.log"

    with open(log_path, "w") as f:
        try:
            _log_line(f, "script", "p5_2_fp16_smoke")
            _log_line(f, "weight_dtype", "float16")
            _log_line(f, "checkpoint_path", str(CHECKPOINT_PATH))
            _log_line(f, "cuda_available", torch.cuda.is_available())

            assert torch.cuda.is_available(), "GPU required for P5.2"
            _log_line(f, "device", torch.cuda.get_device_name(0))

            transformer, sd = load_transformer_fp16(CHECKPOINT_PATH, device="cuda")
            _log_line(f, "model_loaded", True)

            # Runtime dtype verification: at least one parameter must be float16.
            _log_line(f, "weight_dtype_requested", "float16")
            fp16_count = sum(1 for _, p in transformer.named_parameters() if p.dtype == torch.float16)
            _log_line(f, "fp16_param_count", fp16_count)
            _log_line(f, "weight_dtype_actual", "float16" if fp16_count > 0 else "NOT_FLOAT16")
            assert fp16_count > 0, (
                f"P5.2 loader regression: 0 float16 parameters found. "
                "The fp16 load path is broken."
            )

            # Sanity-check: no attn.* missing keys across all blocks.
            if sd is not None:
                model_keys = set(transformer.state_dict().keys())
                ckpt_keys = set(sd.keys())
                assert_attn_weights_loaded(model_keys, ckpt_keys, f)
            else:
                _log_line(f, "attn_missing_keys_count", "skipped")

            hs, eh, seed = generate_or_load_input_seed()
            hs = hs.to("cuda", dtype=torch.float16)
            eh = eh.to("cuda", dtype=torch.float16)
            timestep = torch.tensor([500], device="cuda", dtype=torch.float32)

            _log_line(f, "seed", seed)
            _log_line(f, "input_hidden_states_shape", shape_str(hs))
            _log_line(f, "input_encoder_shape", shape_str(eh))

            transformer.eval()
            t0 = time.time()
            with torch.no_grad():
                out = transformer(hs, timestep=timestep, encoder_hidden_states=eh)
            elapsed = time.time() - t0
            _log_line(f, "forward_seconds", f"{elapsed:.3f}")

            nan, inf = count_nan_inf(out)
            _log_line(f, "output_shape", shape_str(out))
            _log_line(f, "output_dtype", str(out.dtype))
            _log_line(f, "nan_count", nan)
            _log_line(f, "inf_count", inf)
            assert nan == 0 and inf == 0, f"NaN/Inf in output: nan={nan}, inf={inf}"

            _log_line(f, "STATUS", "OK")
            return 0

        except Exception as exc:
            _log_line(f, "error", type(exc).__name__)
            _log_line(f, "error_message", str(exc).replace("\n", " "))
            f.write(traceback.format_exc() + "\n")
            f.write("STATUS=FAIL\n")
            return 1


if __name__ == "__main__":
    sys.exit(main())
